### ISSUE TITLE
NoMethodError: undefined method `to_h' for SemanticLogger::Log

### ISSUE THREAD

**Issue by gingerlime** [rocketjob/semantic_logger#146]
### Environment

* Ruby Version. 2.5.3
* Semantic Logger Version. 4.6.0 (works with with 4.5.0)
* Application/framework names and versions (e.g. Rails, Sinatra, Puma, etc.). Rails 5.2.3
* Rails Semantic Logger Version, if applicable. 4.4.3

In my `config/initializers/logging.rb` I have

```ruby
SemanticLogger.on_log do |log|
  next unless log.try(:level) == :error
  
  Rollbar.error(RuntimeError.new(log.try(:message)), :log_extra => log.to_h)
end
```

With semantic_logger 4.5.0 this works fine, and `log.to_h` produces something like

```
> log.to_h

{:host=>"8c82ffcb7c03",                                                                                                                                                                        :application=>"Semantic Logger",
 :time=>2019-12-30 03:16:17 +0000,
 :level=>:error,                                                                                                                                                                                  :level_index=>4,
 :pid=>46,
 :thread=>"puma 001",                                                                                                                                                                             :file=>"/app/app/controllers/application_controller.rb",
 :line=>36,
 :named_tags=> {:request_id=>"4814d49d-3f40-435f-b841-070345a0e844", :ip=>"42.x.x.x"},
 :name=>"DashboardController",
 :message=>"test"}
```

However, with semantic_logger 4.6.0, I get an error 

```
NoMethodError: undefined method `to_h' for #<SemanticLogger::Log:0x00007f763b2cce10>
```

### Expected Behavior

* `log.to_h` should work the same way it did in <=4.5.0 ?

### Actual Behavior

With semantic_logger >=4.6.0 
```
NoMethodError: undefined method `to_h' for #<SemanticLogger::Log:0x00007f763b2cce10>
```

**Comment by gingerlime** [comment]
Ok, looks like this was deprecated in 4.6.0 ... I wish the [changelog](https://github.com/rocketjob/semantic_logger/blob/master/CHANGELOG.md) was kept up-to-date to notify about breaking changes like these :)

In any case, this seems to be a suitable workaround. If anyone has any feedback, would appreciate it.

```ruby
def log_info(log)
  logger = Struct.new(:host, :application, :environment)
                 .new(
                   SemanticLogger.host,
                   SemanticLogger.application,
                   SemanticLogger.environment
                 )
  SemanticLogger::Formatters::Raw.new.call(log, logger)
end

SemanticLogger.on_log do |log|
  next unless log.try(:level) == :error
  
  Rollbar.error(RuntimeError.new(log.try(:message)), :log_extra => log_info(log))
end
```

**Comment by reidmorrison** [comment]
Do not use `SemanticLogger.on_log` to log to Rollbar, it is not intended for that purpose. `SemanticLogger.on_log` performs calls to Rollbar sequentially in the current thread and will therefore slow down your program unnecessarily.

It would be better to write an Appender for Rollbar. See the Bugsnag appender for an example:
https://github.com/rocketjob/semantic_logger/blob/master/lib/semantic_logger/appender/bugsnag.rb

**Comment by reidmorrison** [comment]
Pull Requests are welcome to keep the changelog up to date with the level of detail you are looking for.

**Comment by gingerlime** [comment]
Thanks @reidmorrison. I really appreciate it.

> ... performs calls to Rollbar sequentially in the current thread and will therefore slow down your program unnecessarily.

Rollbar uses a background job to send the notification, so hopefully pushing a job to log would be relatively quick. We only push to Rollbar for error logs, which aren't frequent.

> It would be better to write an Appender for Rollbar. See the Bugsnag appender for an example:

Yes. I would love to. I contributed to bug fixes to the sentry appender in the past, when we were still using sentry. So I'm familiar with those :) However, as far as I'm aware -- and maybe this changed? -- there's a limitation to appenders losing the rack context? see https://github.com/rocketjob/semantic_logger/issues/97#issuecomment-433373781 in response to [your own comment](https://github.com/rocketjob/semantic_logger/issues/97#issuecomment-376991715). Maybe I missed something there?

**Comment by gingerlime** [comment]
> Pull Requests are welcome to keep the changelog up to date with the level of detail you are looking for.

I'd love to contribute, but I'm not sure how. I'd need to be aware of any changes, ideally before a new release is baked. Tools like dependabot make it really nice to see the changelog on a PR when it's available. Here's an example of what it looks like for one of the gems we use

![Screenshot 2019-12-31 at 08 41 01](https://user-images.githubusercontent.com/524274/71607129-69a35280-2ba9-11ea-8280-9976f3edef21.png)

I found [keep-a-changelog](https://keepachangelog.com/en/1.0.0/) useful in this context. But of course, if you don't think it's important, then maybe best to remove the stale changelog file, or add a comment that it's no longer maintained? just to signal intentions clearly. Happy to submit a PR to do one of those, or to update the changelog retrospectively, based on my limited understanding. Going forward however, I think it requires some coordination to make sure people can contribute changelog updates before the release. Or perhaps you could ask people who contribute PRs to also update the changelog, documenting their own changes? (it till requires coordination, but maybe it offers the least friction?)

In any case, just throwing some ideas here. As I mentioned before, I'd be happy to contribute if you could help guide me how. Thanks for listening, and I know how hard it can be to maintain an open source project.

**Comment by reidmorrison** [comment]
We tried the auto-generator tools for changelogs but they don't do a good job. In fact the original changelog was autogenerated and then had to be "fixed" to make it usable.
Since this is an open source project why don't you take over the full time role of keeping the changelog up to date every time a new gem is created?

**Comment by gingerlime** [comment]
Hi @reidmorrison sorry for the delay. Happy to take on the role of keeping the changelog up to date. It would only be useful if you let me know before you release any minor/major version, so I can make the necessary updates to the changelog. Otherwise a retrospective changelog is not that useful after a new version is already out.

That said, I can definitely try to "backport" the changelog and cover the latest changes. Shall I create a PR for it? I might need some help with a few changes that I'm not necessarily super-familiar with, but will do my best.

Going forward, would be nice to get commit access if I'm "officially" a maintainer of the project.

How does that sound to you then?

**Comment by gingerlime** [comment]
I created a first [PR](https://github.com/rocketjob/semantic_logger/pull/151), just to get initial feedback and see if this is the right kind of updates you're happy with.

**Comment by reidmorrison** [comment]
Thank you for the changelog PR, how would you feel about submitting a PR to add `.to_h` back to the `SemanticLogger::Log` class that matches the previous behavior?

**Comment by reidmorrison** [comment]
Looking at your comment in https://github.com/rocketjob/semantic_logger/issues/97 it would make sense in this case to use `on_log` for Rollbar since it needs to be executed within the thread that has the error. Since it is error level only it is only called at error level and not for all info messages etc.

Is there a way to make this a "standard" feature that either self-installs for anyone that is running Rollbar, or is easily added through a documented feature?

**Comment by gingerlime** [comment]
Hi @reidmorrison sorry for the delay... 

> Is there a way to make this a "standard" feature that either self-installs for anyone that is running Rollbar, or is easily added through a documented feature?

Sounds interesting, but I'm not sure I follow you completely... Ideally, the appender (e.g. Sentry, Bugsnag, Rollbar if we create one), would do this if you set the right level, right? But the problem with using appenders highlighted on #97 is that the backtrace context is lost ... and that's where `on_log` comes in handy (but has its own limitations, like you mentioned). So how can we square that circle? I'm not sure I understand... 

> Thank you for the changelog PR, how would you feel about submitting a PR to add .to_h back to the SemanticLogger::Log class that matches the previous behavior?

If you think having a `to_h` on the class, then I'd be happy to add it back in. I'll try to send a PR.

Side note: I still want to fill the gaps in the changelog. I'm glad that you merged the last one in, so will continue and from that point, the changelog will be up-to-date... I'm then happy to continue to "maintain" it, as long as I'm posted about changes, new releases etc :)

**Comment by reidmorrison** [comment]
@gingerlime Thank you for the `#to_h` fix. 

Do you want to document how to use the `#on_log` option for anyone that is using Rollbar?
Maybe in `docs/appenders.rb`? We could mention it does not use the traditional appender approach so that the thread context is available to Rollbar.

**Comment by gingerlime** [comment]
That's a good idea. I wasn't aware of this readme file.

It's not only for Rollbar though, but for any error tracker (or any case where you need the extra context)... Is there a way to pass this context from the main thread so that appenders can also use it? this might be a better long-term solution, wouldn't it? (although I'm not sure what it means to accomplish that).

**Comment by reidmorrison** [comment]
Each error framework like Rollbar will have their own thread local variables that they hold the instance information in. We could theoretically copy across their thread context information by grabbing the thread local variables and supplying them to Rollbar when calling it's api.
I suspect this would be complex and unless the Rollbar api directly supports it then upgrades would be messy. Just adding it to `#on_log` for now would the safest / simplest approach.

Eventually these error frameworks will have to address thread context information since anytime a new thread is created it will lose the original thread context information. They will have to add the ability to capture, copy, and supply the context information to their api's.

**Comment by reidmorrison** [comment]
Added the documentation from https://github.com/rocketjob/semantic_logger/commit/6dcf65b56be1059b46dade47f80bb7b59ca9011a
